"""Renamed models names from prural names to singilura names

Revision ID: 17c776a1554c
Revises: 650a268d7967
Create Date: 2023-09-04 14:23:47.439771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c776a1554c'
down_revision = '650a268d7967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
